/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as ConfirmationRouteImport } from './routes/confirmation'
import { Route as ConfigureRouteImport } from './routes/configure'
import { Route as CheckoutRouteImport } from './routes/checkout'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdminIndexRouteImport } from './routes/admin.index'
import { Route as LegalShippingRouteImport } from './routes/legal.shipping'
import { Route as LegalReturnsRouteImport } from './routes/legal.returns'
import { Route as LegalMentionsRouteImport } from './routes/legal.mentions'
import { Route as LegalCookiesRouteImport } from './routes/legal.cookies'
import { Route as LegalConfidentialiteRouteImport } from './routes/legal.confidentialite'
import { Route as LegalCgvRouteImport } from './routes/legal.cgv'
import { Route as AdminProductsRouteImport } from './routes/admin.products'
import { Route as AdminOrdersIndexRouteImport } from './routes/admin.orders.index'
import { Route as AdminOrdersIdRouteImport } from './routes/admin.orders.$id'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfirmationRoute = ConfirmationRouteImport.update({
  id: '/confirmation',
  path: '/confirmation',
  getParentRoute: () => rootRouteImport,
} as any)
const ConfigureRoute = ConfigureRouteImport.update({
  id: '/configure',
  path: '/configure',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutRoute = CheckoutRouteImport.update({
  id: '/checkout',
  path: '/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalShippingRoute = LegalShippingRouteImport.update({
  id: '/legal/shipping',
  path: '/legal/shipping',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalReturnsRoute = LegalReturnsRouteImport.update({
  id: '/legal/returns',
  path: '/legal/returns',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalMentionsRoute = LegalMentionsRouteImport.update({
  id: '/legal/mentions',
  path: '/legal/mentions',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCookiesRoute = LegalCookiesRouteImport.update({
  id: '/legal/cookies',
  path: '/legal/cookies',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalConfidentialiteRoute = LegalConfidentialiteRouteImport.update({
  id: '/legal/confidentialite',
  path: '/legal/confidentialite',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalCgvRoute = LegalCgvRouteImport.update({
  id: '/legal/cgv',
  path: '/legal/cgv',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminProductsRoute = AdminProductsRouteImport.update({
  id: '/admin/products',
  path: '/admin/products',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIndexRoute = AdminOrdersIndexRouteImport.update({
  id: '/admin/orders/',
  path: '/admin/orders/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminOrdersIdRoute = AdminOrdersIdRouteImport.update({
  id: '/admin/orders/$id',
  path: '/admin/orders/$id',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/configure': typeof ConfigureRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/configure': typeof ConfigureRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/admin': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders': typeof AdminOrdersIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/checkout': typeof CheckoutRoute
  '/configure': typeof ConfigureRoute
  '/confirmation': typeof ConfirmationRoute
  '/contact': typeof ContactRoute
  '/login': typeof LoginRoute
  '/admin/products': typeof AdminProductsRoute
  '/legal/cgv': typeof LegalCgvRoute
  '/legal/confidentialite': typeof LegalConfidentialiteRoute
  '/legal/cookies': typeof LegalCookiesRoute
  '/legal/mentions': typeof LegalMentionsRoute
  '/legal/returns': typeof LegalReturnsRoute
  '/legal/shipping': typeof LegalShippingRoute
  '/admin/': typeof AdminIndexRoute
  '/admin/orders/$id': typeof AdminOrdersIdRoute
  '/admin/orders/': typeof AdminOrdersIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/checkout'
    | '/configure'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/admin/products'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/returns'
    | '/legal/shipping'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/orders/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/checkout'
    | '/configure'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/admin/products'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/returns'
    | '/legal/shipping'
    | '/admin'
    | '/admin/orders/$id'
    | '/admin/orders'
  id:
    | '__root__'
    | '/'
    | '/checkout'
    | '/configure'
    | '/confirmation'
    | '/contact'
    | '/login'
    | '/admin/products'
    | '/legal/cgv'
    | '/legal/confidentialite'
    | '/legal/cookies'
    | '/legal/mentions'
    | '/legal/returns'
    | '/legal/shipping'
    | '/admin/'
    | '/admin/orders/$id'
    | '/admin/orders/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CheckoutRoute: typeof CheckoutRoute
  ConfigureRoute: typeof ConfigureRoute
  ConfirmationRoute: typeof ConfirmationRoute
  ContactRoute: typeof ContactRoute
  LoginRoute: typeof LoginRoute
  AdminProductsRoute: typeof AdminProductsRoute
  LegalCgvRoute: typeof LegalCgvRoute
  LegalConfidentialiteRoute: typeof LegalConfidentialiteRoute
  LegalCookiesRoute: typeof LegalCookiesRoute
  LegalMentionsRoute: typeof LegalMentionsRoute
  LegalReturnsRoute: typeof LegalReturnsRoute
  LegalShippingRoute: typeof LegalShippingRoute
  AdminIndexRoute: typeof AdminIndexRoute
  AdminOrdersIdRoute: typeof AdminOrdersIdRoute
  AdminOrdersIndexRoute: typeof AdminOrdersIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/confirmation': {
      id: '/confirmation'
      path: '/confirmation'
      fullPath: '/confirmation'
      preLoaderRoute: typeof ConfirmationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/configure': {
      id: '/configure'
      path: '/configure'
      fullPath: '/configure'
      preLoaderRoute: typeof ConfigureRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout': {
      id: '/checkout'
      path: '/checkout'
      fullPath: '/checkout'
      preLoaderRoute: typeof CheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/shipping': {
      id: '/legal/shipping'
      path: '/legal/shipping'
      fullPath: '/legal/shipping'
      preLoaderRoute: typeof LegalShippingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/returns': {
      id: '/legal/returns'
      path: '/legal/returns'
      fullPath: '/legal/returns'
      preLoaderRoute: typeof LegalReturnsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/mentions': {
      id: '/legal/mentions'
      path: '/legal/mentions'
      fullPath: '/legal/mentions'
      preLoaderRoute: typeof LegalMentionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cookies': {
      id: '/legal/cookies'
      path: '/legal/cookies'
      fullPath: '/legal/cookies'
      preLoaderRoute: typeof LegalCookiesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/confidentialite': {
      id: '/legal/confidentialite'
      path: '/legal/confidentialite'
      fullPath: '/legal/confidentialite'
      preLoaderRoute: typeof LegalConfidentialiteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/cgv': {
      id: '/legal/cgv'
      path: '/legal/cgv'
      fullPath: '/legal/cgv'
      preLoaderRoute: typeof LegalCgvRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/products': {
      id: '/admin/products'
      path: '/admin/products'
      fullPath: '/admin/products'
      preLoaderRoute: typeof AdminProductsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/': {
      id: '/admin/orders/'
      path: '/admin/orders'
      fullPath: '/admin/orders/'
      preLoaderRoute: typeof AdminOrdersIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/orders/$id': {
      id: '/admin/orders/$id'
      path: '/admin/orders/$id'
      fullPath: '/admin/orders/$id'
      preLoaderRoute: typeof AdminOrdersIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CheckoutRoute: CheckoutRoute,
  ConfigureRoute: ConfigureRoute,
  ConfirmationRoute: ConfirmationRoute,
  ContactRoute: ContactRoute,
  LoginRoute: LoginRoute,
  AdminProductsRoute: AdminProductsRoute,
  LegalCgvRoute: LegalCgvRoute,
  LegalConfidentialiteRoute: LegalConfidentialiteRoute,
  LegalCookiesRoute: LegalCookiesRoute,
  LegalMentionsRoute: LegalMentionsRoute,
  LegalReturnsRoute: LegalReturnsRoute,
  LegalShippingRoute: LegalShippingRoute,
  AdminIndexRoute: AdminIndexRoute,
  AdminOrdersIdRoute: AdminOrdersIdRoute,
  AdminOrdersIndexRoute: AdminOrdersIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
